- name: Provision
  gather_facts: false
  hosts: cluster
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  roles:
    - role: mucsi96.kubetools.new_ssh_user
      vars:
        private_key_file: "{{ inventory_dir }}/.ssh/id_ed25519"
        ansible_user: root
        ansible_ssh_pass: "{{ initial_password }}"
        ansible_port: "{{ initial_port }}"

    - role: mucsi96.kubetools.ssh_hardening
      vars:
        ansible_port: "{{ initial_port }}"
        ansible_user: "{{ username }}"

    - role: mucsi96.kubetools.gather_facts
      vars:
        ansible_port: "{{ ssh_port }}"

    - role: mucsi96.kubetools.update_packages

    - role: mucsi96.kubetools.install_kubernetes
      vars:
        local_kube_config: "{{ inventory_dir }}/.kube/config"

    - role: mucsi96.kubetools.deploy_kubernetes_sso_portal

    - role: mucsi96.kubetools.deploy_cloudflare_tunnel
      vars:
        tunnel_name: "{{ subdomain }}"

    - role: mucsi96.kubetools.deploy_kubenetes_monitoring
