alias ap='ansible-playbook'
alias ave='ansible-vault encrypt vars/vault.yaml inventory'
alias avd='ansible-vault decrypt vars/vault.yaml inventory'
alias avv='ansible-vault view vars/vault.yaml '
alias avvi='ansible-vault view inventory'
alias ct='cloudflared tunnel'